/// <reference types="vitest/config" />
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

// The build goes straight into the integration, because that folder is the
// only thing HACS installs. It is committed; CI rebuilds it and fails if the
// result differs, so the shipped bundle is always the one this source makes.
const OUT_DIR = '../custom_components/better_wall_dashboard/frontend';

// The languages the dashboard itself speaks; see src/lib/i18n.ts.
const LANGUAGES = new Set(['en', 'de']);
const STUB = '\0bwd-empty-locale';

/**
 * Leave ha-component-kit's other translations out of the build.
 *
 * It carries Home Assistant's frontend strings for about sixty languages,
 * 300 kB each, for its own `localize()` -- which this dashboard never calls,
 * having its own strings. Every one of them would still ship: 19 MB that HACS
 * downloads to every install. Only the languages the dashboard speaks are
 * kept; any other resolves to an empty table, which the kit handles as "no
 * translations" rather than as an error.
 */
function onlyOurLanguages(): Plugin {
  return {
    name: 'bwd-only-our-languages',
    enforce: 'pre',
    resolveId(source, importer) {
      if (!importer?.replace(/\\/g, '/').includes('@hakit/core/dist/es/hooks/useLocale/locales/')) return null;
      const match = source.match(/^\.\/([A-Za-z-]+)\/\1\.js$/);
      return match && !LANGUAGES.has(match[1]) ? STUB : null;
    },
    load(id) {
      return id === STUB ? 'export default {};' : null;
    },
  };
}

const LOADER = 'better_wall_dashboard.js';

/**
 * Write the file Home Assistant loads: a loader, outside the module graph.
 *
 * Home Assistant loads it as `better_wall_dashboard.js?v=<fingerprint>`, and
 * that query string is part of a module's identity. When this file was a
 * real entry chunk, the bundler put shared code in it (its own preload
 * helper, for one) and every other chunk imported that code back -- from
 * `better_wall_dashboard.js`, without the query. The browser took that for a
 * different module and loaded a second copy of the whole app, React included,
 * and the editor's hooks called a React that was not rendering: a black page.
 *
 * Written as a plain asset, the loader is nothing any chunk can import. It
 * records the URL it was loaded under (for the reload check) and imports the
 * real entry by its content-hashed name.
 */
function entryLoader(): Plugin {
  return {
    name: 'bwd-entry-loader',
    apply: 'build',
    generateBundle(_options, bundle) {
      const boot = Object.values(bundle).find(chunk => chunk.type === 'chunk' && chunk.isEntry && chunk.name === 'boot');
      if (!boot) this.error('no boot chunk to load');
      const source = [
        '// Generated by vite.config.ts (entryLoader). Loads the dashboard; imported by nothing.',
        'globalThis.__betterWallDashboardEntry = import.meta.url;',
        `import(new URL(${JSON.stringify(`./${boot.fileName}`)}, import.meta.url).href);`,
        '',
      ].join('\n');
      this.emitFile({ type: 'asset', fileName: LOADER, source });
    },
  };
}

export default defineConfig({
  // Relative, so every chunk and asset is resolved against the URL the entry
  // module was loaded from. The integration serves the build under its own
  // route, and nothing here should have to know what that route is.
  base: './',
  plugins: [react(), onlyOurLanguages(), entryLoader()],
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    target: 'es2022',
    // One entry of ~180 kB gzipped is what a panel is: React, the kit and the
    // dashboard, loaded once per page and cached by fingerprint after that.
    chunkSizeWarningLimit: 800,
    modulePreload: false,
    // A module, not a page: there is no index.html to emit. The real entry
    // is boot, named after its contents like every other chunk; the file
    // Home Assistant loads is the loader written by entryLoader() below.
    rolldownOptions: {
      input: { boot: 'src/panel/boot.ts' },
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      },
    },
  },
  test: {
    include: ['src/**/*.test.ts'],
  },
});
