// Generated by vite.config.ts (entryLoader). Loads the dashboard; imported by nothing.
globalThis.__betterWallDashboardEntry = import.meta.url;
import(new URL("./assets/boot-Br3vhTq2.js", import.meta.url).href);
