// Generated by vite.config.ts (entryLoader). Loads the dashboard; imported by nothing.
globalThis.__betterWallDashboardEntry = import.meta.url;
import(new URL("./assets/boot-B6KKY-_w.js", import.meta.url).href);
